# Generated by Django 2.1.5 on 2019-02-12 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=255)),
                ('re_date', models.DateTimeField()),
                ('body', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=12)),
                ('status', models.IntegerField(default=0)),
                ('grev_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
