# Generated by Django 2.1.5 on 2019-02-17 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0002_grievance_verifeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievance',
            name='verifeedback',
        ),
    ]
