# Generated by Django 2.1.5 on 2019-02-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0003_remove_grievance_verifeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='verifeedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
