# Generated by Django 2.1.5 on 2019-02-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0004_grievance_verifeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='position',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='resolvefeedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
