# Generated by Django 2.1.5 on 2019-02-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0005_auto_20190219_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='user',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='verified',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
