# Generated by Django 2.1.5 on 2019-02-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0006_auto_20190219_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
