# Generated by Django 2.1.5 on 2019-02-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0007_grievance_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='r_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
