# Generated by Django 2.1.5 on 2019-02-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0008_grievance_r_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='v_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
